### ISSUE TITLE
2016 Review

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-super-snow#4]
Need to do a full review of this plugin and make sure it is still compatible with the latest version of WordPress. I'd also like to cleanup the UI just a bit this year.

**Comment by jaswsinc** [comment]
![2015-12-04_00-29-31](https://cloud.githubusercontent.com/assets/1563559/11586285/67a8e0ec-9a1e-11e5-9d1e-a6cd2328e089.png)

---

![2015-12-04_00-29-55](https://cloud.githubusercontent.com/assets/1563559/11586286/67ab2c9e-9a1e-11e5-8da8-7bb1b8cc83e8.png)

---

![2015-12-04_00-30-17](https://cloud.githubusercontent.com/assets/1563559/11586287/68003cde-9a1e-11e5-8be8-eb158be3411f.png)

**Comment by raamdev** [comment]
Sweeeeeet! :grinning:
