### ISSUE TITLE
Plugin don't work on WP 4.3.1 with Microsoft IIS 7.0

### ISSUE THREAD

**Issue by Drunik01** [websharks/wp-super-snow#6]
Hello!
Plugin not working on WordPress 4.3.1 with the theme evolve.
Previously on version WP 3.7 it worked fine.
Wordpress installed on the IIS Microsoft 7.0.
How can I see what the problem is?
Thank you in advance!

**Comment by jaswrks** [comment]
@Drunik01 Thanks for the report.

When you say, "not working", can you explain what that means exactly? What symptoms have you observed, if any, that makes you think it's not working?

Also, can you please take a look at the Virtual Snow Blower panel in your configuration and paste the list of image paths that have for me please? Thanks! :-)

**Comment by Drunik01** [comment]
Thanks for the answer.
The plugin is installed and activated, all settings are standard, but the page is not visible snowflakes.
I also installed a plugin ZenCache - i turn it off and delete cached pages - it did not help.
File snow.min.js?ver=151204 is added to the page, I checked.

![wp-super-snow](https://cloud.githubusercontent.com/assets/12659847/11612775/588e80ac-9c18-11e5-8261-80c1bb85f9b3.png)

**Comment by Drunik01** [comment]
Sorry, I made a mistake - IIS version is 8.5 and PHP 5.5.8

**Comment by jaswrks** [comment]
> but the page is not visible snowflakes

Thank you. I was unable to reproduce this behavior in a clean installation of WordPress.

Can you enable WP Super Snow and then send me a link to a page where it should be snowing? I can run JavaScript diagnostics there and see what might be happening on your end.

**Comment by Drunik01** [comment]
Hi!
My website - k-maslo.ru - the main page should show the snow - the plugin is acive now.
There are a lot of different plugins could interfere, although other plugins with snow I've tried worked fine, but I did not like them.
First I set the plugin through the plugin Manager, then I downloaded the source code of the plugin from the github website and changed the calls "wp-super-snow.min.js" on "wp-super-snow.js" and etc.
If you want I can do a clean install from plugin Manager.
Thanks in advance!

**Comment by jaswrks** [comment]
Thank you.

Inspecting your site in the Google Chrome Developer Console, I'm seeing JavaScript errors in other parts of the page that could be causing WP Super Snow not to work as expected. Resolve those errors and it's likely that WP Super Snow will magically start to work then :-)

![2015-12-08_02-52-05](https://cloud.githubusercontent.com/assets/1563559/11655033/da2098be-9d56-11e5-8cba-19e3cf1d6a93.png)

**Comment by Drunik01** [comment]
Thank you very much!
I put the update for the plugin Huge IT lightbox and your plugin started to work!
Thanks again for your work, merry Christmas and happy New Year!

**Comment by jaswrks** [comment]
Same to you :-)
